---
# https://backstage.io/docs/features/software-catalog/descriptor-format#kind-group
apiVersion: backstage.io/v1alpha1
kind: Group
metadata:
  name: api-developers
  description: API Developer Portal users
spec:
  type: team
  profile:
    displayName: API Developers
  children: []
---
# https://backstage.io/docs/features/software-catalog/descriptor-format#kind-user
apiVersion: backstage.io/v1alpha1
kind: User
metadata:
  name: admin
spec:
  profile:
    displayName: Admin User
    email: admin@opencode.local
  memberOf: [api-developers]
---
# https://backstage.io/docs/features/software-catalog/descriptor-format#kind-user
apiVersion: backstage.io/v1alpha1
kind: User
metadata:
  name: developer1
spec:
  profile:
    displayName: Developer One
    email: developer1@opencode.local
  memberOf: [api-developers]
